# i3blocks config

# Global
markup=pango
separator=false
separator_block_width=10

# Disk usage
[disk]
label=   
instance=/
command=~/.config/i3/scripts/disk
interval=30
min_width= 999G

# Memory usage
[memory]
label=   
command=~/.config/i3/scripts/memory
interval=2
min_width= 100

[cpu_usage]
label=  
command=~/.config/i3/scripts/cpu_usage
interval=2
min_width= 100%

[CPU-temperature]
label=
command=~/.config/i3/scripts/temperature
interval=30
min_width= 100.0°C

# Network (your label was a CPU icon)
[bandwidth]
label=
command=~/.config/i3/scripts/bandwidth2
interval=persist
min_width= aa999.9M

# Battery
[battery]
label=  
command=~/.config/i3/scripts/battery1
interval=30
min_width= 100%

[pavucontrol]
full_text=
command=pavucontrol
interval=once
min_width=  

[keybindings]
full_text=  
command=~/.config/i3/scripts/keyhint
interval=once
min_width=  

[ppd_menu]
full_text= 
command=~/.config/i3/scripts/power-profiles
color=#407437
interval=once
min_width=

[ppd-status]
command=~/.config/i3/scripts/ppd-status
interval=5
min_width=power-saver

[time]
command=date '+%a %d %b %H:%M:%S'
interval=1
min_width=seg 12 jan 00:00:00

[shutdown_menu]
full_text= 
command=~/.config/i3/scripts/powermenu
interval=once
min_width=

